language: bash # TIL that if you don't want to use language, use "minimal" or "bash".
branches: master

install: true
 
script: 
    - |
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE '(\.xaml$)'
      then
        echo "No xaml file changed. Aborting!"
        exit
      fi
    - rm -rf en
    - zip pack.zip */ -r   
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: pack.zip
  skip_cleanup: true
  tag_name: $TRAVIS_BUILD_NUMBER
  name: Build $TRAVIS_BUILD_NUMBER – $(date +'%Y/%m/%d %H:%M:%S')
  body: $TRAVIS_COMMIT
